name: Daily Journal

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run journal script
        run: python journal.py

      - name: Commit journal entry
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add journal/
          git commit -m "Auto journal entry" || echo "No changes to commit"
          git push
name: Daily Journal

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run journal script
        run: python journal.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add journal/
          git commit -m "Daily journal update" || echo "No changes"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
